default: &default
  adapter: postgresql
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mollika_dev
  username: <%= Rails.application.credentials.dig(:mollika_database, :username) %>
  password: <%= Rails.application.credentials.dig(:mollika_database, :password) %>
  host: 127.0.0.1
  port: 5432
  schema_search_path: mollika, public

test:
  <<: *default
  database: mollika_test
  schema_search_path: mollika, public
  username: <%= Rails.application.credentials.dig(:mollika_database, :username) %>
  password: <%= Rails.application.credentials.dig(:mollika_database, :password) %>

production:
  primary:
    <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  schema_search_path: salehobe,public
  # cache:
  #   <<: *default
  #   database: storage/production_cache.sqlite3
  #   migrations_paths: db/cache_migrate
  # queue:
  #   <<: *default
  #   database: storage/production_queue.sqlite3
  #   migrations_paths: db/queue_migrate
  # cable:
  #   <<: *default
  #   database: storage/production_cable.sqlite3
  #   migrations_paths: db/cable_migrate
