default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  schema_search_path: mollika, public

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  schema_search_path: mollika, public

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_search_path: mollika,public
